###
GET http://localhost:9000/api/asd@gmail.com HTTP/1.1

###
POST http://localhost:9000/api/registeruser HTTP/1.1
Content-Type: application/json

{
    "nombre": "qwe",
    "apellido": "qwe",
    "email": "asd@gmail.com",
    "numero": "123",
    "contrasena": "asd"
}

###
DELETE http://localhost:9000/api/qwe HTTP/1.1

###
PUT http://localhost:9000/api/asd HTTP/1.1
Content-Type: application/json

{
    "nombre": "asd",
    "apellido": "zxc",
    "email": "asd@gmail.com",
    "numero": "123",
    "contrasena": "asd"
}
